-- V2: 建立 listings 資料表
CREATE TABLE listings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    idol_group VARCHAR(100),
    member_name VARCHAR(100),
    album VARCHAR(100),
    era VARCHAR(100),
    version VARCHAR(50),
    card_code VARCHAR(50),
    is_official BOOLEAN DEFAULT TRUE,
    `condition` CHAR(1) CHECK (`condition` IN ('S', 'A', 'B', 'C')),
    photos JSON,
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    locked_by_proposal_id BIGINT,
    tags JSON,
    created_by BIGINT,
    updated_by BIGINT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_owner (owner_id),
    INDEX idx_status (status),
    INDEX idx_idol_group (idol_group),
    INDEX idx_member_name (member_name),
    INDEX idx_condition (`condition`),
    INDEX idx_locked_by_proposal (locked_by_proposal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
